### ISSUE TITLE
Run in my local machine

### ISSUE THREAD

**Issue by Meghesh** [airavata-courses/distributors#13]
Hey distributors,

Can I run your code in my local machine.

Thanks-
Meghesh

**Comment by harshallpandit** [comment]
Sure. Did you check our wiki pages dedicated to each microservice?
Please follow the instructions and let me know if you face any issues.
Also, for quick testing, we have a wiki page called `Testing Project 1`.

**Comment by Meghesh** [comment]
Checked Testing Project 1, just wanted to know if i can do it in my local machine.

**Comment by harshallpandit** [comment]
Follow these instructions -

https://github.com/airavata-courses/distributors/wiki/Jersey-Service

https://github.com/airavata-courses/distributors/wiki/Node-JS-Microservice

I have not hosted the Python service, I'll update you once I get in touch with my teammates.

**Comment by sagarpanchal8793** [comment]
Hello Meghesh,

The Python service is up and running. Also the instructions for the same is present in the Testing Project 1 wiki page. Please test it and let me know if you face any issues on the same.

**Comment by Meghesh** [comment]
Running on Testing Project 1
