### ISSUE TITLE
Testing link required

### ISSUE THREAD

**Issue by ljosyula** [airavata-courses/distributors#17]
Please share the testing link for the project

**Comment by harshallpandit** [comment]
Here is the link - 

https://github.com/airavata-courses/distributors/wiki/Testing-Project-1

**Comment by ljosyula** [comment]
Tested fetching of the books, finding all the users, to find a particular user and deleting the user through the given link, functioning as expected.

finding users:

![find_all_users](https://user-images.githubusercontent.com/42261978/46056079-efba2900-c11c-11e8-8953-e86288995774.JPG)
 finding 1 user :

![find_one_users](https://user-images.githubusercontent.com/42261978/46056084-f2b51980-c11c-11e8-9b6a-b100b16c7732.JPG)
getting books:

![get_books](https://user-images.githubusercontent.com/42261978/46056087-f47edd00-c11c-11e8-80ba-dcd5f97cc65e.JPG)
deleting user :

![delete_user](https://user-images.githubusercontent.com/42261978/46056073-ecbf3880-c11c-11e8-8255-c7a9b506a0cf.JPG)

**Comment by ljosyula** [comment]
Tested graphIQL, all the queries are getting executed as expected.

![graphiql_getuserprofile](https://user-images.githubusercontent.com/42261978/46056580-4fb1cf00-c11f-11e8-823a-b22d62517098.JPG)

**Comment by harshallpandit** [comment]
Great! if you have tested everything, could you please close the issue?

**Comment by ljosyula** [comment]
Tested Python server, it is working as expected
![python_server](https://user-images.githubusercontent.com/42261978/46056998-66f1bc00-c121-11e8-948a-3778c028cac4.JPG)

**Comment by ljosyula** [comment]
-Tested getbooks implemented through Java Jersey via the link provided, it is working as expected.
- Tested user level changes and updates via graphIQL
- Tested querying of the users by cloning python branch, working fine.

great work!
closing the issue
